[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
todo-server-sdk = { path = "todo-server-sdk" }
hyper = { version = "0.14", features = ["server", "tcp"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
mockall = "0.14.0"
async-trait = "0.1.89"
chrono = "0.4.44"
csv = "1.3"
uuid = { version = "1.23.1", features = ["v4"] }
tower-http = { version = "0.4", features = ["fs"] }
tower = "0.4"
axum = "0.6"
http = "0.2"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls", "macros"] }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
oauth2 = { version = "4", features = ["reqwest"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
jsonwebtoken = "9"
tower-cookies = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls", "ring", "webpki-roots", "smtp-transport", "builder"] }
askama = "0.16.0"
thiserror = "2.0.19"
rrule = "0.14.0"
async-recursion = "1.1.1"
ical = "0.10"
chrono-tz = "0.10"

