[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prl"
path = "src/main.rs"

[dependencies]
todo-client = { path = "../todo-client" }
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
chrono = "0.4"
tokio = { version = "1.53.0", features = ["macros", "rt-multi-thread"] }
