use async_trait::async_trait;
use std::path::PathBuf;

#[derive(Debug)]
pub enum StoreError {
    NotFound,
    Internal(String),
}

/// Where attachment *bytes* live — separate from `sqlite::AttachmentRepo`, which only
/// ever holds metadata (filename, size, the `storage_key` below). Keeping the two apart
/// is what makes it possible to swap the blob backend later (e.g. an S3-compatible
/// implementation once this project is open-sourced) without touching `AttachmentRepo`,
/// `service::attachments`, or any handler — see root CLAUDE.md's Attachments section.
///
/// `key` is an opaque string this trait's own `put` implementation chooses and hands
/// back to the caller to persist (as `Attachment::storage_key`); nothing outside a store
/// implementation ever constructs or parses one itself.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait AttachmentStore: Send + Sync {
    async fn put(&self, key: &str, bytes: Vec<u8>) -> Result<(), StoreError>;
    async fn get(&self, key: &str) -> Result<Vec<u8>, StoreError>;
    async fn delete(&self, key: &str) -> Result<(), StoreError>;
}

/// Backed by a plain directory on disk at `root`. Deliberately not aware of whether
/// `root` is local disk or a network share (SMB/NFS) mounted at that path — the OS
/// presents both identically to `tokio::fs`, so a self-hoster who wants attachments on a
/// NAS rather than the app server's own disk just points `TODO_ATTACHMENTS_DIR` at the
/// mount point; no code path here changes. See root CLAUDE.md's Attachments section for
/// the Synology-mount setup this is meant to work with.
pub struct LocalFsAttachmentStore {
    root: PathBuf,
}

impl LocalFsAttachmentStore {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// Every `key` this store ever sees was generated by `service::attachments`
    /// (uuid-based — see `generate_storage_key`), so this rejection is defensive, not
    /// load-bearing: a `key` containing `..` or an absolute path would otherwise let a
    /// caller escape `root` entirely, turning a bad lookup into an arbitrary filesystem
    /// read/write.
    fn path_for(&self, key: &str) -> Result<PathBuf, StoreError> {
        if key.contains("..") || key.starts_with('/') {
            return Err(StoreError::Internal(format!(
                "invalid attachment storage key: {key}"
            )));
        }
        Ok(self.root.join(key))
    }
}

#[async_trait]
impl AttachmentStore for LocalFsAttachmentStore {
    async fn put(&self, key: &str, bytes: Vec<u8>) -> Result<(), StoreError> {
        let path = self.path_for(key)?;
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent)
                .await
                .map_err(|e| StoreError::Internal(e.to_string()))?;
        }
        tokio::fs::write(&path, bytes)
            .await
            .map_err(|e| StoreError::Internal(e.to_string()))
    }

    async fn get(&self, key: &str) -> Result<Vec<u8>, StoreError> {
        let path = self.path_for(key)?;
        match tokio::fs::read(&path).await {
            Ok(bytes) => Ok(bytes),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Err(StoreError::NotFound),
            Err(e) => Err(StoreError::Internal(e.to_string())),
        }
    }

    async fn delete(&self, key: &str) -> Result<(), StoreError> {
        let path = self.path_for(key)?;
        match tokio::fs::remove_file(&path).await {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(StoreError::Internal(e.to_string())),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_root(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "todo-attachment-store-test-{name}-{}",
            uuid::Uuid::new_v4()
        ));
        dir
    }

    #[tokio::test]
    async fn put_then_get_roundtrips() {
        let root = temp_root("roundtrip");
        let store = LocalFsAttachmentStore::new(&root);

        store
            .put("proj1/item1/file.txt", b"hello".to_vec())
            .await
            .unwrap();
        let bytes = store.get("proj1/item1/file.txt").await.unwrap();
        assert_eq!(bytes, b"hello");

        tokio::fs::remove_dir_all(&root).await.ok();
    }

    #[tokio::test]
    async fn get_missing_key_returns_not_found() {
        let root = temp_root("missing");
        let store = LocalFsAttachmentStore::new(&root);

        let err = store.get("nope").await.unwrap_err();
        assert!(matches!(err, StoreError::NotFound));

        tokio::fs::remove_dir_all(&root).await.ok();
    }

    #[tokio::test]
    async fn delete_is_idempotent() {
        let root = temp_root("delete");
        let store = LocalFsAttachmentStore::new(&root);

        store.put("a/b.txt", b"x".to_vec()).await.unwrap();
        store.delete("a/b.txt").await.unwrap();
        store.delete("a/b.txt").await.unwrap();

        tokio::fs::remove_dir_all(&root).await.ok();
    }

    #[tokio::test]
    async fn rejects_path_traversal_keys() {
        let root = temp_root("traversal");
        let store = LocalFsAttachmentStore::new(&root);

        let err = store.put("../escape.txt", b"x".to_vec()).await.unwrap_err();
        assert!(matches!(err, StoreError::Internal(_)));

        tokio::fs::remove_dir_all(&root).await.ok();
    }
}
